### ISSUE TITLE
Does not convert "dotted" properties

### ISSUE THREAD

**Issue by code0100fun** [lorcan/test-selectors-codemod#4]
Here is an example:

```javascript
import {
  create,
  text,
  visitable,
} from 'ember-cli-page-object';
import testSelector from 'ember-test-selectors';

const url = '/foo';

const SELECTOR = 'bar';
const SELECTORS = {
  bar: 'bar',
};

export default create({
  url,
  visit: visitable(url),
  text1: text(testSelector(SELECTOR)),
  text2: text(testSelector(SELECTORS.bar)),
});
```

Notice the single level variable gets converted correctly but the "dotted" property that should become ``text(`[data-test-${SELECTORS.bar}]`)`` is blanked out:

```javascript
import {
  create,
  text,
  visitable,
} from 'ember-cli-page-object';

const url = '/foo';

const SELECTOR = 'bar';
const SELECTORS = {
  bar: 'bar',
};

export default create({
  url,
  visit: visitable(url),
  text1: text(`[data-test-${SELECTOR}]`),
  text2: text(), // <-- here
});
```

**Comment by lorcan** [comment]
That looks pretty bad. Should be generating in this case?
```
text2: text(`[data-test-${SELECTOR.bar}`),
```

Any chance you could put together a failing test?

**Comment by code0100fun** [comment]
I have examples [here](https://github.com/code0100fun/test-selectors-codemod/blob/blank-conversion/transforms/__testfixtures__/remove-test-selector-helper.input.js#L29).

I've noticed that numbers also blank out so I added that to the test as well.

I can take a shot at a fix later unless you want me to just PR the broken tests for you to work on.

![image](https://user-images.githubusercontent.com/820991/32006200-147ec4b4-b974-11e7-90a7-db219d315b90.png)

**Comment by lorcan** [comment]
If you provided fixes I'd happily merge them :-)
Not sure how much time in the short-term I'd get to work on it myself...
