### ISSUE TITLE
Documentation for running without git clone

### ISSUE THREAD

**Issue by iezer** [lorcan/test-selectors-codemod#7]
People may find it easier to run the transform without having to clone the repo. There's a way to do that in the [es5-getter-ember-codemod docs](https://github.com/rondale-sc/es5-getter-ember-codemod#installation) Thanks @rondale-sc

If you like this idea I can update the README.

```
npm install -g jscodeshift
jscodeshift -t https://rawgit.com/lorcan/test-selectors-codemod/master/transforms/remove-test-selector-helper.js ./tests
```

**Comment by lorcan** [comment]
Great idea @iezer! I think that's a great option!
