### ISSUE TITLE
Remove imports as well

### ISSUE THREAD

**Issue by astronomersiva** [lorcan/test-selectors-codemod#9]
First of all, thanks a ton for this! Really saved a lot of time :) I would like to suggest removing the import statements as well.  

`import testSelector from 'appName/tests/helpers/ember-test-selectors';`

Most projects will have ESLint enabled and just removing the helper will cause ESLint failures.

**Comment by lorcan** [comment]
Hi @astronomersiva, glad you found the tool useful. 
Would you be able to put together a PR with a failing test (or even better, a fix)? We're open for contributions :-)

**Comment by astronomersiva** [comment]
On it 👍
